prueba_homepage:
    path:     /
    defaults: { _controller: pruebaBundle:Default:index }

prueba_db:
    path:     /db
    defaults: { _controller: pruebaBundle:Default:db }

prueba_op:
    path:     /op
    defaults: { _controller: pruebaBundle:Default:op }
